# Generated by aqua-cli/scripts/package.sh. Do not edit.
class Aqua < Formula
  desc "Transcribe audio and manage Aqua Voice settings from the terminal"
  homepage "https://aquavoice.com/docs/cli"
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://updates.aquavoice.com/cli/v1.0.1/aqua_darwin_arm64.tar.gz"
      sha256 "c35ed549119b9994402381e74e257cee00d8e8aa55796a0ca078ba21f32edaa8"
    end
    on_intel do
      url "https://updates.aquavoice.com/cli/v1.0.1/aqua_darwin_amd64.tar.gz"
      sha256 "adb221ff42c65020b03f810f7a7da26ad81fc8eed0aabe1a7be5e100e2823d00"
    end
  end

  on_linux do
    on_arm do
      url "https://updates.aquavoice.com/cli/v1.0.1/aqua_linux_arm64.tar.gz"
      sha256 "f56b488ac03cbeac6031eba491320054743ec4a25defe62fe4f2f1ace5729f8e"
    end
    on_intel do
      url "https://updates.aquavoice.com/cli/v1.0.1/aqua_linux_amd64.tar.gz"
      sha256 "745cdcff751744fd1348c4f49895caaf65a2c20802efee10c2b77bc1399f8eed"
    end
  end

  conflicts_with "aqua", because: "both install an aqua binary"

  def install
    bin.install "aqua"
    generate_completions_from_executable(bin/"aqua", "completion")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/aqua --version")
  end
end
