# Generated by aqua-cli/scripts/package.sh. Do not edit.
class Aqua < Formula
  desc "Transcribe audio and manage Aqua Voice settings from the terminal"
  homepage "https://aquavoice.com/docs/cli"
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://updates.aquavoice.com/cli/v1.0.0/aqua_darwin_arm64.tar.gz"
      sha256 "088e4c6169ae7b49ab3adb1aec6c4df1aa23814e5c8f432d7f1f327d9f835053"
    end
    on_intel do
      url "https://updates.aquavoice.com/cli/v1.0.0/aqua_darwin_amd64.tar.gz"
      sha256 "959d0f81104334018c7678fc87fd8a26aaac446e4a885444ba5e70215b46b94d"
    end
  end

  on_linux do
    on_arm do
      url "https://updates.aquavoice.com/cli/v1.0.0/aqua_linux_arm64.tar.gz"
      sha256 "30408fb4a1054d5cf58a6588073c9c04d99ffbdc0998d0d4463deac10f92799d"
    end
    on_intel do
      url "https://updates.aquavoice.com/cli/v1.0.0/aqua_linux_amd64.tar.gz"
      sha256 "af6f910cd5212785b4ad979e79580655d89aebbf1f02ad0d51424c9f3ae77377"
    end
  end

  conflicts_with "aqua", because: "both install an aqua binary"

  def install
    bin.install "aqua"
    generate_completions_from_executable(bin/"aqua", "completion")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/aqua --version")
  end
end
